FROM python:3.11-slim

WORKDIR /app

# 파이썬 패키지 설치
COPY requirements_api.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 코드 복사
COPY api_server.py .
COPY db.py .
COPY .env .

# Flask 앱 실행
CMD ["python", "api_server.py"]